plugins {
    id 'me.champeau.jmh' version '0.7.2'
}

version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(23)
    }
}

dependencies {
    implementation project(':fsmp4j')
}

jmh {
    jmhVersion = '1.37'
    // select benchmarks with a regex, e.g. ./gradlew jmh -Pbenchmarks='PoolBenchmark.get'
    includes = [project.findProperty('benchmarks') ?: '.*']
    resultFormat = 'JSON'
}
